### ISSUE TITLE
Where is function reflect()？

### ISSUE THREAD

**Issue by Nabla-GIT** [ferminLR/webgpu-path-tracing#1]
Hi,ferminLR,

you did a great job with your Path tracing project！

**I'm learning your code，and I cant find the function of reflect() in the file of compute.js**

where you defined it?

**Comment by ferminLR** [comment]
Hi @Nabla-GIT, and thanks for your words! :)

The `reflect()` function is part of the WGSL language, so I did't have to define it.

Here you have a link to the docs: https://www.w3.org/TR/WGSL/#reflect-builtin
